require:
  - rubocop-performance
  - rubocop-rake

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - pgdice.gemspec

# TODO: Evaluate if this is an acceptable parameter list. It's a constructor after all.
Metrics/ParameterLists:
  Exclude:
    - lib/pgdice/table.rb

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'examples/**/*'
