# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/ruby:2.5.1

  - image: circleci/postgres:10.4-alpine-ram
    environment:

jobs:
  tests:
    <<: *defaults
    steps:
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - gem-cache-{{ arch }}-{{ .Branch }}
        - gem-cache

    - run:
        name: Setup dependencies
        command: |
          bundle install --jobs 4 --retry 3

    - save_cache:
        paths:
        - vendor/bundle
        key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

    - attach_workspace:
        at: ~/repo/tmp

    - run:
        name: Run tests
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "test/**/*_test.rb" | circleci tests split --split-by=timings)"

          bundle exec rake test




workflows:
  version: 2
  commit:
    jobs:
    - tests
