approved_tables:
- table_name: comments
  past: 1
  future: 0
  column_name: created_at
  period: day
- table_name: posts
  past: 10
  future: 0
  column_name: created_at
  period: day # day, month, year