#database_url: <%= ENV['PGDICE_DATABASE_URL'] %>
#table_drop_batch_size: 7
approved_tables:
- table_name: comments
  past: 90
  future: 14
  column_name: created_at
  period: day
- table_name: posts
  past: 2
  future: 2
  column_name: created_at
  period: year